name: Dungeon
version: 0.0.1
description: Dungeon Maker.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  stagexl: any
  stagexl_flump: any
  stagexl_richtextfield: any
  stagexl_spine: any
transformers:
- $dart2js:
    commandLineOptions:
    - --trust-type-annotations
    minify: true
